package tui

import (
	"context"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	tea "charm.land/bubbletea/v2"

	"spettro/internal/agent"
	"spettro/internal/telegram"
)

// dispatchTelegramEvent decides which observability events get mirrored to
// every bound Telegram chat. The default is concise: final assistant
// output, plans, comments, errors, banners, ask-user / approval notices.
// Tool traces are suppressed (they would spam the chat).
//
// Called from publishRemote. All outbound HTTP work happens on a worker
// goroutine inside telegramBroadcastAsync so the bubbletea Update loop is
// never blocked by a Bot API round trip.
func (m *Model) dispatchTelegramEvent(kind string, data map[string]any) {
	if m.telegramRelay == nil {
		return
	}
	if !m.telegramRelay.AnySubscriber() {
		return
	}
	switch kind {
	case "assistant_message":
		content, _ := data["content"].(string)
		if strings.TrimSpace(content) != "" {
			m.telegramBroadcastAsync(telegram.Prefix("🤖", content))
		}
	case "assistant_error":
		errStr, _ := data["error"].(string)
		if errStr != "" {
			m.telegramBroadcastAsync(telegram.Prefix("⚠️ error", errStr))
		}
	case "plan":
		plan, _ := data["plan"].(string)
		if strings.TrimSpace(plan) != "" {
			m.telegramBroadcastAsync(telegram.Prefix("📋 plan", plan))
		}
	case "plan_error":
		errStr, _ := data["error"].(string)
		if errStr != "" {
			m.telegramBroadcastAsync(telegram.Prefix("⚠️ plan error", errStr))
		}
	case "comment":
		msg, _ := data["message"].(string)
		if strings.TrimSpace(msg) != "" {
			m.telegramBroadcastAsync(telegram.Prefix("💬", msg))
		}
	case "banner":
		level, _ := data["level"].(string)
		switch level {
		case "warn", "error":
			text, _ := data["text"].(string)
			if text != "" {
				m.telegramBroadcastAsync(telegram.Prefix("⚠️", text))
			}
		}
	case "ask_user":
		question, _ := data["question"].(string)
		options, _ := data["options"].([]string)
		ctxStr, _ := data["context"].(string)
		def, _ := data["default"].(string)
		parts := []string{"❓ Spettro is asking:", question}
		if ctxStr != "" {
			parts = append(parts, "", ctxStr)
		}
		if len(options) > 0 {
			parts = append(parts, "", "Options:")
			for _, opt := range options {
				marker := "•"
				if def != "" && opt == def {
					marker = "★"
				}
				parts = append(parts, "  "+marker+" "+opt)
			}
		}
		parts = append(parts, "", "Reply here with your answer (free-text).")
		m.telegramBroadcastAsync(strings.Join(parts, "\n"))
		// Arm the answer router for every bound chat: the next non-slash
		// message resolves the dialog. ExpectAnswer is cheap (in-memory
		// map under a mutex) so we run it inline rather than on the
		// outbound worker goroutine.
		for _, chatID := range m.telegramRelay.BoundChats() {
			m.telegramRelay.ExpectAnswer(chatID, true)
		}
	case "approval_request":
		cmd, _ := data["command"].(string)
		reason, _ := data["reason"].(string)
		text := "🔐 shell approval required\n  command: " + telegram.Truncate(cmd, 1000)
		if reason != "" {
			text += "\n  reason:  " + reason
		}
		text += "\n\nApprove or deny inside the TUI."
		m.telegramBroadcastAsync(text)
	case "commit":
		msg, _ := data["message"].(string)
		if msg != "" {
			m.telegramBroadcastAsync(telegram.Prefix("🟢 commit", msg))
		}
	case "commit_error":
		errStr, _ := data["error"].(string)
		if errStr != "" {
			m.telegramBroadcastAsync(telegram.Prefix("🔴 commit error", errStr))
		}
	case "state":
		if m.telegramRelay.Config().Verbose {
			reason, _ := data["reason"].(string)
			if reason != "" {
				m.telegramBroadcastAsync("[state] " + reason)
			}
		}
	case "tool":
		if !m.telegramRelay.Config().Verbose {
			return
		}
		name, _ := data["name"].(string)
		status, _ := data["status"].(string)
		if name == "" || status == "" {
			return
		}
		m.telegramBroadcastAsync(fmt.Sprintf("🔧 %s — %s", name, status))
	}
}

// telegramBroadcastAsync sends text on a worker goroutine so the TUI's
// Update loop is never blocked by a Bot API round trip. Errors surface
// through relay.LastSendError() and `/telegram status`.
func (m *Model) telegramBroadcastAsync(text string) {
	relay := m.telegramRelay
	if relay == nil || strings.TrimSpace(text) == "" {
		return
	}
	go relay.Broadcast(text)
}

// dispatchTelegramMedia inspects a completed tool trace and, when it came
// from one of the media-generation tools (`grok-image` / `grok-video`),
// uploads the produced files to every bound Telegram chat.
//
// Files generated by the agent live under the workspace root using
// workspace-relative paths; we resolve them against m.cwd before handing
// them to the relay. The uploads happen on background goroutines so the
// bubbletea Update loop is never blocked by the Bot API round trip.
//
// Captions are short: one line with the prompt (truncated), so the user
// sees what was generated without inflating the chunk count.
func (m *Model) dispatchTelegramMedia(t agent.ToolTrace) {
	if m.telegramRelay == nil || !m.telegramRelay.AnySubscriber() {
		return
	}
	if t.Status != "success" {
		return
	}
	kind, ok := mediaKindForTool(t.Name)
	if !ok {
		return
	}
	files, prompt := parseMediaTraceOutput(t.Output)
	if len(files) == 0 {
		return
	}
	caption := mediaCaption(t.Name, prompt)
	for _, rel := range files {
		abs := mediaAbsolutePath(m.cwd, rel)
		if abs == "" {
			continue
		}
		// Always use the file extension to override the tool's "kind" if
		// the agent picked an unusual format (e.g. `.gif` from
		// grok-image). This keeps Telegram from rejecting payloads with a
		// content-type/method mismatch.
		extKind := telegram.ClassifyMedia(abs)
		actualKind := extKind
		if extKind == telegram.MediaKindDocument {
			actualKind = kind
		}
		filePath := abs
		mediaKind := actualKind
		mediaCaption := caption
		go m.telegramRelay.BroadcastMedia(filePath, mediaKind, mediaCaption)
	}
}

// mediaKindForTool maps a tool ID to the natural MediaKind to use when
// uploading. Returns (_, false) for tools that should never trigger an
// upload.
func mediaKindForTool(toolName string) (telegram.MediaKind, bool) {
	switch toolName {
	case "grok-image":
		return telegram.MediaKindImage, true
	case "grok-video":
		return telegram.MediaKindVideo, true
	}
	return "", false
}

// parseMediaTraceOutput extracts the saved file paths and prompt from the
// JSON envelope that grok-image / grok-video emit on success. The envelope
// looks like:
//
//	{"tool":"grok-image","model":"grok-imagine-image-quality","prompt":"...","count":1,"files":["assets/foo.png"]}
//
// On parse error (truncated JSON, etc.) the returned slice is empty —
// callers treat that as "nothing to send" rather than surfacing a noisy
// error in the chat.
func parseMediaTraceOutput(output string) (files []string, prompt string) {
	output = strings.TrimSpace(output)
	if output == "" {
		return nil, ""
	}
	var payload struct {
		Files  []string `json:"files"`
		Prompt string   `json:"prompt"`
	}
	if err := json.Unmarshal([]byte(output), &payload); err != nil {
		return nil, ""
	}
	out := make([]string, 0, len(payload.Files))
	for _, f := range payload.Files {
		f = strings.TrimSpace(f)
		if f != "" {
			out = append(out, f)
		}
	}
	return out, strings.TrimSpace(payload.Prompt)
}

// mediaCaption renders a concise Telegram caption from a tool name and the
// originating prompt. Captions are capped to 1024 chars by Telegram; we
// pre-trim to a friendlier 400-char preview so multiple files in one batch
// don't make the chat history feel like a wall of text.
func mediaCaption(toolName, prompt string) string {
	prompt = strings.TrimSpace(prompt)
	if prompt == "" {
		return ""
	}
	preview := telegram.Truncate(prompt, 400)
	switch toolName {
	case "grok-image":
		return "🖼 " + preview
	case "grok-video":
		return "🎬 " + preview
	}
	return preview
}

// mediaAbsolutePath resolves a workspace-relative path against cwd. When
// the input is already absolute (or cwd is empty) the input is returned as
// is. The function does not call os.Stat — Telegram's upload layer
// performs that check and surfaces a proper error if the file is gone.
func mediaAbsolutePath(cwd, p string) string {
	p = strings.TrimSpace(p)
	if p == "" {
		return ""
	}
	if filepath.IsAbs(p) {
		return p
	}
	if cwd == "" {
		return p
	}
	return filepath.Join(cwd, p)
}

// telegramClearAnswerExpectations is called when the pending ask-user
// dialog resolves (either via TUI input or via a Telegram answer), so the
// relay stops routing non-slash text as answers.
func (m *Model) telegramClearAnswerExpectations() {
	if m.telegramRelay == nil {
		return
	}
	for _, chatID := range m.telegramRelay.BoundChats() {
		m.telegramRelay.ExpectAnswer(chatID, false)
	}
}

// telegramAutostartDoneMsg delivers the result of the asynchronous relay
// startup (relay.Start performs a blocking getMe round-trip).
type telegramAutostartDoneMsg struct {
	relay *telegram.Relay
	err   error
}

// autostartTelegram is called once during New() when the user has previously
// enabled the relay. It constructs the relay (cheap, no network) and returns a
// tea.Cmd that performs the blocking relay.Start off the UI thread, delivering
// a telegramAutostartDoneMsg. Returns nil when autostart is disabled or no
// token is configured. Previously this ran relay.Start synchronously, freezing
// the very first paint for up to 15s on a slow getMe.
func (m *Model) autostartTelegram() tea.Cmd {
	cfg, err := telegram.LoadConfig()
	if err != nil {
		return nil
	}
	if !cfg.AutoStart {
		return nil
	}
	token, err := telegram.LoadToken()
	if err != nil || strings.TrimSpace(token) == "" {
		return nil
	}
	relay, err := telegram.NewRelay(telegram.Options{
		Token:       token,
		BotUsername: cfg.BotUsername,
		Config:      cfg,
	})
	if err != nil {
		return nil
	}
	return func() tea.Msg {
		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer cancel()
		if err := relay.Start(ctx); err != nil {
			return telegramAutostartDoneMsg{err: err}
		}
		return telegramAutostartDoneMsg{relay: relay}
	}
}

// handleTelegramAutostartDone applies the async relay startup result: on
// success it adopts the relay and pumps its channels into the loop; on failure
// it surfaces a quiet system message (the user can still run /telegram start).
func (m Model) handleTelegramAutostartDone(msg telegramAutostartDoneMsg) (tea.Model, tea.Cmd) {
	if msg.err != nil {
		m.pushSystemMsg("telegram autostart failed: " + msg.err.Error())
		m.refreshViewport()
		return m, nil
	}
	m.telegramRelay = msg.relay
	m.pushSystemMsg("telegram relay resumed — bot @" + msg.relay.BotUsername())
	m.refreshViewport()
	return m, tea.Batch(telegramListenCmds(msg.relay)...)
}
